name: Deploy version.json to GitHub Pages

permissions:
  contents: write-all

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate version.json
        run: |
          python util/extract_version.py
          echo "✅ version.json created:"
          cat version.json

      - name: Save version.json for transfer
        run: cp version.json /tmp/version.json

      - name: Checkout bh-pages branch
        run: |
          git fetch origin bh-pages
          git checkout bh-pages || git checkout --orphan bh-pages
          git reset --hard

      - name: Move version.json to docs/ and commit
        run: |
          mkdir -p docs
          cp /tmp/version.json docs/version.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/version.json
          git status
          git commit -m "Update version.json in docs on bh-pages" || echo "No changes to commit"
          git push origin bh-pages
