name: Deploy version.json to scoqx.github.io

permissions:
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TARGET_REPO: scoqx/scoqx.github.io
  TARGET_BRANCH: master
  GIT_USER_NAME: GitHub Actions
  GIT_USER_EMAIL: actions@github.com

jobs:
  deploy-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo (source)
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate version.json
        run: |
          python util/extract_version.py
          echo "✅ version.json created:"
          cat version.json

      - name: Проверка наличия PAT
        run: |
          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "❌ Секрет PERSONAL_ACCESS_TOKEN отсутствует или пустой"
            exit 1
          else
            echo "✅ Секрет PERSONAL_ACCESS_TOKEN доступен"
            echo "Длина токена: ${#PERSONAL_ACCESS_TOKEN}"
          fi
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - name: Checkout target repo scoqx.github.io
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: target-repo

      - name: Copy version.json to target repo root
        run: |
          cp version.json target-repo/version.json

      - name: Commit and push to target repo
        run: |
          cd target-repo
          git config user.name "${{ env.GIT_USER_NAME }}"
          git config user.email "${{ env.GIT_USER_EMAIL }}"
          git add version.json
          git diff --quiet --cached || git commit -m "Update version.json [auto]"
          git push origin ${{ env.TARGET_BRANCH }}
