name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:  # ← Добавлено для ручного запуска через GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract version and create version.json
        run: |
          python /util/extract_version.py
          echo "✅ Version file created:"
          cat version.json

      - name: Commit version.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.json
          git commit -m "Update version.json" || echo "No changes to commit"

      - name: Push changes to master
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs 
          publish_branch: gh-pages
          force_orphan: true
