name: Deploy version.json to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Добавлено для ручного запуска через GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract version and create version.json
        run: |
          python util/extract_version.py
          echo "✅ Version file created:"
          cat version.json

      - name: Commit version.json to gh-pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Checkout gh-pages branch
          git fetch origin gh-pages
          git checkout gh-pages
          # Copy version.json from the master branch
          cp ../version.json .
          git add version.json
          git commit -m "Update version.json" || echo "No changes to commit"
          # Push changes to gh-pages
          git push origin gh-pages

