name: Telegram Notify on Push

on:
  push:
    branches:
      - main

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Отправка сообщения в Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          COMMIT_URL="${{ github.head_commit.url }}"
          COMMIT_MSG="${{ github.head_commit.message }}"
          COMMIT_AUTHOR="${{ github.head_commit.author.name }}"
          REPO_NAME="${{ github.repository }}"
          GITHUB_ACTOR="${{ github.actor }}"

          MESSAGE="✅ *Новый коммит в репозитории* _${REPO_NAME}_\n\n👤 Автор: *${COMMIT_AUTHOR}*\n🧑‍💻 От пользователя: \`${GITHUB_ACTOR}\`\n\n💬 Сообщение:\n\`\`\`\n${COMMIT_MSG}\n\`\`\`\n🔗 [Смотреть коммит](${COMMIT_URL})"

          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"
